<?php 
use App\Services\RedisService;
?>
<!DOCTYPE html>
<head>
    <title>Movie items</title>
</head>
<body>
        <?php 
            $redis = new RedisService();
            $redis = $redis->getService();
            $item = null;
            if(isset($_GET['id'])) {
                $item = json_decode($redis->get('/v1/items/' . $_GET['id']), TRUE);
            }
        ?>
        <?php if (!isset($item)): ?>
            <b>No item found!</b>
        <?php else: ?>
            <div class="item">
                <dl>
                    <dt>ID: <dd><?php echo $item['id'] ?>
                    <dt>Title: <dd><?php echo $item['title']?>
                    <dt>Synopsis: <dd><?php echo $item['synopsis']?>
                </dl>
            </div>
        <?php endif ?>
</body>
</html>